version: '3.9'

services:
  postgres:
    container_name: pg_soonun
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: soonungift
      POSTGRES_PASSWORD: soonungift
      POSTGRES_DB: soonungift
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgres/data


volumes:
  pgdata: {}